name: first-workflow
on: workflow-dispatch
jobs: 
  first-job:
  run-on: ubuntu-latest
  steps:
    - name: print hello message
      run: echo "hi gagan!"
    - name: print bye message
      run: echo "bye gagan!"
