name: test workflowwww
on: workflow-dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: |
          echo "hi gagan"
          echo "bye gagan"
  
